name: "✨ Feature Request"
description: "Suggest an idea for this project "
title: "Feat:"
labels: ["feature"]
body:
  - type: textarea
    attributes:
      label: "Describe the feature"
      description:
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Screenshots/Videos(if applicable)"
      description: "Share some screenshots or a video to explain the issue that you're experiencing."
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: "Record"
      options:
        - label: "I agree to follow this project's Code of Conduct"
          required: true
        - label: "I want to work on this issue"